import Head from "next/head";
import { Box } from "@chakra-ui/react";

import ShareModal from "src/components/Modals/ShareModal";
import HomePage from "src/components/HomePage";
import { fetchAPI } from "src/utils/api";

const Home = ({ articles, categories, homepage }) => {
  console.log("\nFETCH RESPONSES:", {
    articles,
    categories,
    homepage,
  });
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage
        articles={articles}
        categories={categories}
        homepage={homepage}
      />
      <ShareModal />
    </Box>
  );
};

export async function getStaticProps() {
  // Run API calls in parallel
  const [articlesRes, categoriesRes, homepageRes] = await Promise.all([
    fetchAPI("/articles", { populate: ["image", "category"] }),
    fetchAPI("/categories", { populate: "*" }),
    fetchAPI("/homepage", {
      populate: {
        seo: { populate: "*" },
        // featured_post: { populate: "*" },
        featured_post: {
          populate: { article: { populate: "image" } },
        },
      },
    }),
  ]);

  return {
    props: {
      articles: articlesRes.data,
      categories: categoriesRes.data,
      homepage: homepageRes.data,
    },
    revalidate: 1,
  };
}

export default Home;
