import Head from "next/head";
import { Box } from "@chakra-ui/react";

import ShareModal from "src/components/Modals/ShareModal";
import HomePage from "src/components/HomePage";
import { fetchAPI } from "src/utils/api";

const Home = ({ homepage }) => {
  // console.log("\nFETCH RESPONSES:", { homepage });

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage homepage={homepage} />
      <ShareModal />
    </Box>
  );
};

export async function getStaticProps() {
  const homepageRes = await fetchAPI("/homepage", {
    populate: {
      featured_post: {
        populate: { article: "*" },
      },
    },
  });

  return {
    props: {
      homepage: homepageRes.data,
    },
    revalidate: 1,
  };
}

export default Home;
